# Generated by Django 4.1.7 on 2023-03-13 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0016_remove_order_date_order_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
