# Generated by Django 4.1.7 on 2023-03-14 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0017_alter_order_date_created_alter_order_date_updated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
